-- Staging Tasks
ALTER TASK SHOPFLOW_DB.STAGING.TSK_ROOT_PIPELINE SUSPEND;
ALTER TASK SHOPFLOW_DB.STAGING.TSK_LOAD_STG_ORDER_ITEMS SUSPEND;
ALTER TASK SHOPFLOW_DB.STAGING.TSK_LOAD_STG_WEB_EVENTS SUSPEND;
ALTER TASK SHOPFLOW_DB.STAGING.TSK_LOAD_STG_ORDERS SUSPEND;


-- Dynamic Marts Tables
ALTER DYNAMIC TABLE SHOPFLOW_DB.MARTS.DT_CUSTOMER_COHORTS SUSPEND;
ALTER DYNAMIC TABLE SHOPFLOW_DB.MARTS.DT_DAILY_REVENUE SUSPEND;
ALTER DYNAMIC TABLE SHOPFLOW_DB.MARTS.DT_TOP_PRODUCTS SUSPEND;
